const express = require("express")
const app = express()
const urlRoute = require("./routes/url.js")
const { connectToMongoDb } = require("./connection.js")
const PORT = 8001
connectToMongoDb("mongodb://localhost:27017/short-url")
    .then(() => console.log("mongo conntected Saifur"))
app.use(express.json())
app.use("/url", urlRoute)
app.listen(PORT, ()=> console.log("Server started listening at PORT "))